### PR TITLE
Fix Circle and Ellipse resolution

### LINKED ISSUE #420: Two.Circle only works properly with 5 vertices
The `Two.Circle` constructor won't make a circle if passed a number of vertices other than 5.

Here it is with 5 vertices:
image

But with 4 vertices, it appears triangular:
image

With 8 vertices, it looks like a heptagon:
image

At higher numbers of vertices, it starts intersecting itself:
image

What's weird is that the number of "vertices" of the resulting shape is one less than the number of vertices passed.

It looks like this was introduced by [this commit](https://github.com/jonobr1/two.js/commit/310bd14cc65a81ac831bfee7083a9c453838a4aa).

### PR DESCRIPTION
**Pull request by adroitwhiz**
Resolves #420 

- In circle.js and ellipse.js, instead of declaring the "circle coefficient" for a 4-vertex approximation at the top of the file, the correct "circle coefficient" for the circle or ellipse's number of vertices is now calculated in `_update`.
  - I also took this opportunity to hoist calculations that don't vary per-vertex out of the vertex processing loop (e.g. calculating radius).

- Circles and ellipses are now cyclic paths instead of having the start/end vertices at the same position.
  - This will probably cause another #383. I think a good solution is to add a flag that determines whether closed shapes should stay closed when their `ending` !== 1.

- `Path.getBoundingClientRect` has been fixed to handle cyclic paths, like the ones now used in circles and ellipses.

I have not exposed `resolution` as a parameter in `Two.makeCircle` and `Two.makeEllipse`. Is it a good idea to do so?

### CODE REVIEW

**Comment by jonobr1** [comment]
This makes a lot of sense and I totally agree with you that `if (path.ending !== 1)` would be the right condition in the `Two.Path._update` function to address the difference. I also agree that having the cyclical setup that you've described is overall more "logical" to the developer and serves as a precedent for future shapes that may have this issue. Thanks!

**Comment by jonobr1** [comment]
I exposed the `resolution` in the two `make` functions. Good eye! I think it makes sense to offer developers a way to control that if they'd like.

**Comment by adroitwhiz** [comment]
Merge conflicts have been resolved

**Comment by jonobr1** [comment]
Sorry, I thought I merged this into `dev`, but did the opposite 😅 

Thanks for merging the conflicts!

**Pull request merged**
