### PR TITLE
Fixed typographical error, changed accomodate to accommodate in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
jonobr1, I've corrected a typographical error in the documentation of the [two.js](https://github.com/jonobr1/two.js) project. You should be able to merge this pull request automatically. However, if this was intentional or you enjoy living in linguistic squalor please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by jonobr1** [comment]
:+1: Appreciate it! Next time can you PR into the `dev` branch?

**Comment by jonobr1** [comment]
I hate living in typographic squalor, ew!

**Comment by thoppe** [comment]
The process by @orthographic-pedant is mostly automated. I found that it makes the most sense to submit the PR to the default branch for a generic repository. Since it is a minor fix, most people don't seem to mind merging in directly.

**Comment by jonobr1** [comment]
that's amazing.

**Pull request merged**
