### PR TITLE
fix global detection to work in strict mode

### PR DESCRIPTION
**Pull request by trusktr**

### CODE REVIEW

**Comment by trusktr** [comment]
Ah, but there's `System.global` stage 3. We should detect `System.global` if that becomes official.

**Comment by trusktr** [comment]
I think this needs to be built, and build files added too.

**Comment by trusktr** [comment]
I tested this by modifying the bundle output after building with Rollup.

**Comment by trusktr** [comment]
For now I just run this `postinstall` script and all works fine:

```js
#!/usr/bin/env node

// a function wrapper is needed for older versions of Node.
~function() {
    "use strict"

    const fs = require('fs')
    const path = require('path')
    const filePath = path.resolve('node_modules', 'two.js', 'build', 'two.js')

    let data = fs.readFileSync(filePath).toString()

    data = data.replace(
        /var root = this/g,
        "var root = typeof window != 'undefined' ? window : typeof global != 'undefined' ? global : null"
    )

    fs.writeFileSync(filePath, data)
}()
```

**Comment by GoToLoop** [comment]
Oh... `~` in place of `void`.  :-P

**Comment by jonobr1** [comment]
Looks good, thanks for helping out!

**Pull request merged**
