### PR TITLE
Fix Two.Element type

### PR DESCRIPTION
**Pull request by cyndra0**
See: #628 .

I simply made small changes to `types.d.ts` and it works great in my local codebase. I was a little hesitant about whether to open this PR, however, because it seems like the dts file would need to be changed manually after they were generated. But I think it might help you a little In some way ;)

### CODE REVIEW

**Comment by jonobr1** [comment]
This is awesome, thanks so much for both the issue and the PR. This works fine with adding and removing objects from a group as well?

**Comment by jonobr1** [comment]
Oh, I see it's just for the root class. I'll update this on the group.

You're right, at the moment I need to make manual changes after the compilation process. But, once I know everything that needs changing it should be straightforward to write a script that just does text replaces of what I'm doing manually now.

**Comment by cyndra0** [comment]
Thanks for your reply @jonobr1 !

> This works fine with adding and removing objects from a group as well?
Nope because I forgot this case... and don't forget to doublecheck if there's any other module affected before next release. 

btw, it would be better if more types could be exported from the module "two.js", which will allow use cases like:
```ts
import Two, { Text } from 'two.js'
```
instead of what we are doing now:
```ts
import Two from 'two.js'
import { Text } from 'two.js/src/text'
// or:
declare var text: typeof Two.Text
```
If you want to do typescript optimization in the future, you can consider about it:)

**Comment by jonobr1** [comment]
Wouldn't that package the whole library instead of using each individual
module and be able to tree shake?

The Types aren't set up this way, but you can do something like that in ES6:

```javascript
import Two from 'two.js';

Two.Text
```

**Comment by cyndra0** [comment]
> Wouldn't that package the whole library instead of using each individual module and be able to tree shake?

What I actually mean is the way types are set up. This has nothing to do with the generated js code and tree shaking, and only affects typescript users.  As for my use case above, I'm trying to access the type rather than the constructor function (similar to: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export). Using `typeof Two.Text` is not bad, but there is some redundancy in the code.

**Comment by jonobr1** [comment]
Got it. I think [this commit](https://github.com/jonobr1/two.js/commit/5e9120613a374dafb73b5fe88aee6db3482ddad5) would fix that then, right? So now you can do:

```javascript
import Two, { Text } from 'two.js';
```

**Pull request merged**
