### PR TITLE
Fix nodelist readonly length

### PR DESCRIPTION
**Pull request by larrybotha**
When running Two.js in an environment where `use strict;` is used, setting `childNodes.length` to anything throws an error because it's actually a read-only property.

Also, [`childNodes` is live](https://developer.mozilla.org/en-US/docs/Web/API/NodeList), so updates to the DOM will be reflected in the `length` property automatically.

All tests are passing with this update.

### CODE REVIEW

**Comment by larrybotha** [comment]
haha, ye, I was just about to say hang on a second... I've got a failing case that's not yet tested. Still evaluating the issue... but looks like a gradient is not being applied.

Will follow up once I figure out what's going on.

**Comment by jonobr1** [comment]
I think it should work now. But, if there are additional things you want to add I'll wait to merge. Thanks for the PR!

**Comment by larrybotha** [comment]
cool, I'm gonna merge these changes back into my branch, and see what's going on with the issue I'm experiencing in my project. Hopefully a quick fix, but I'll likely get back to you tomorrow :)

**Comment by larrybotha** [comment]
alright, your commits fixed my issues! Good to go to merge. Thanks @jonobr1

**Pull request merged**
