### PR TITLE
Premultiply WebGL alpha

### LINKED ISSUE #409: Dark fringe around WebGL object edges
Currently, there's a black outline/fringe around objects in the WebGL renderer:

image

This seems to be because `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is disabled, and hence texture sampling occurs before alpha multiplication, leading to [incorrect results](http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/).

[It seems like the code is there, but is disabled, linking to a cryptic Chrome bug I don't have permission to access.](https://github.com/jonobr1/two.js/blob/0a1624eb417bb047849d7eb2061fc4816919f424/src/renderer/webgl.js#L1312)

[Furthermore, it was added in a seemingly unrelated commit.](https://github.com/jonobr1/two.js/commit/027ecba5dcaaf4213779ff2f4f4bc5508bf38611)

### PR DESCRIPTION
**Pull request by adroitwhiz**
Resolves #409 

This PR enables the `gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL` flag.

It updates the blending equations to match--namely, compositing now uses `gl.ONE, gl.ONE_MINUS_SRC_ALPHA`, and masking now uses `gl.ZERO, gl.SRC_ALPHA` (multiply *every* channel by the mask, not just the alpha).

### CODE REVIEW

**Comment by jonobr1** [comment]
In theory this blending mode should work, but on my PC this doesn't actually blend objects in the same manner as the other renderers. I'll post a screenshot.

**Comment by adroitwhiz** [comment]
Here's what it looks like on my PC (Firefox + Chromium, Linux, NVIDIA 440.31 drivers):

Latest dev branch | This PR
-|-
image | image

So still not correct, but closer. The extra bits rendering around the edges are a separate issue.

What does it look like on your PC?

**Comment by jonobr1** [comment]
Sorry for the confusion on this PR. To disambiguate, there are a couple of things going on.

1. In some previous commits to this PR I was able to fix masking in the `WebGLRenderer` and simplify the `gl.stencilOp` functions. This makes it so that there's only one place to call the blend functions when constructing a `Two.WebGLRenderer`. If you want the contribution credit through git you'll need to update your commit to the latest `dev` branch and remove the blend functions in the function `Two.WebGLRenderer.Utils.group.render`.
2. The conflict between the blend function you're proposing (which was the original blend functions in Two.js until just a few months ago) is that they actually blend differently than in SVG or Canvas2d. I've added comparisons below to make it more clear. The problem, as you outlined in [Issue 409](https://github.com/jonobr1/two.js/issues/409), is that the `gl.blendFuncSeparate` I added -- which has a more parity in blending for transparent elements -- has the dark fringes.

Capture
_Left: `blendFuncSeparate(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA);`
Right: `blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);`_

As you can see, the left version where there is a darker ring keeps parity with other renderers here, but has dark fringes. The right version blends incorrectly but doesn't have dark fringes.

One minor point, is that the `gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, gl.TRUE);` doesn't really have much effect in either scenario, but I accept re-enabling until otherwise known. The Chromium bug you mentioned was deleted and was written prior to the divergence of webkit (I believe).

At this point I'm not sure what's better or worse. But, what's nice is that it's easy for the developer to decide for themselves. For instance, in their application they could say:

```javascript
var two = new Two({ type: Two.Types.webgl }).appendTo(document.body);
var gl = two.renderer.ctx;
gl.blendEquation(gl.FUNC_ADD);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
// This overwrites the general blending function in your session
// to solve the dark fringes
```

Anyway, if you make the changes described, I'd be happy to merge your commits in. Otherwise, you're free to overwrite the blend functions as you see fit based on the above code snippet. Thanks again for posting and sorry for the confusion on this PR! 👍

**Comment by adroitwhiz** [comment]
The problem is that `gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, gl.TRUE); ` doesn't do anything because `gl.pixelStorei` takes a regular Boolean, not a GL boolean.

If you instead do `gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, true); `, it should work.

**Comment by jonobr1** [comment]
See https://github.com/jonobr1/two.js/pull/413 for updated answer.

**Pull request closed without merging**
