### PR TITLE
Add makeArrow function

### PR DESCRIPTION
**Pull request by mike168m**
Added a function to draw arrows. Found it useful for mathematical illustrations on my blog.
I thought others may find it useful. The implementation is based on Two.Path

### CODE REVIEW

**Comment by jonobr1** [comment]
Super cool, thanks for sharing! I'm sure other people will find it useful. Mind posting a link to your blog on this thread so people can find it easily?

**Comment by mike168m** [comment]
Thanks, here's a link to a post using two
http://rcsmike.com/cellular_automata
 I'm working on another post on graphics primitives which uses the makeArrow function.

**Comment by cirosantilli** [comment]
I wonder why it does not show up on the documentation: https://two.js.org/#documentation

**Comment by jonobr1** [comment]
Because that documentation is out-of-date and currently being updated to pull automatically from the source code's comments.

**Pull request merged**
